---
- name: Check kops version
  shell: "kops version 2>&1 | grep {{ kops_version }}"
  failed_when: false
  changed_when: false
  register: kops_versions_match

- include: download.yml
  when: kops_versions_match.rc != 0

- name: copy kops to /usr/local/bin/
  copy:
    remote_src: yes
    src: /tmp/kops-linux-amd64
    dest: /usr/local/bin/kops
    owner: root
    group: root
    mode: 0755
  when: kops_versions_match.rc != 0
...
